### ISSUE TITLE
[Feature] Re-download failed downloads after the download is done

### ISSUE THREAD

**Issue by jmpt16** [notFaad/coom-dl#12]
Recover all timed out downloads after the successful downloads are done.
Also, add a custom number of retries.

**Comment by spreagit** [comment]
upvote!

**Comment by notFaad** [comment]
Added as a feature

**Comment by notFaad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Feature] Auto Download failed downloads](https://trello.com/c/0gfwoXNT/3-feature-auto-download-failed-downloads)
