### ISSUE TITLE
No Pictures

### ISSUE THREAD

**Issue by KingSplyce** [notFaad/coom-dl#15]
it is only downloading videos and no pictures

**Comment by CRCODE22** [comment]
Same problem no pictures even tough it said it downloaded more than 1500 files only 3 arrived.

**Comment by putridterror** [comment]
I'm not getting images either, though videos seem to be downloading fine.

I wonder if it has to do with this announcement: https://coomer.su/cardfans-and-co

**Comment by c3bb6f719742fd1e5768d6d1361cfb49** [comment]
Would be perfect with pictures

**Comment by ari-greensoul** [comment]
It doesn't download images for me either, only videos. I hope the program is corrected soon, if it worked it would be wonderful.

**Comment by notFaad** [comment]
Fixed with 0.72
