### ISSUE TITLE
[Feature] users should select legacy file naming mode

### ISSUE THREAD

**Issue by zackfee** [notFaad/coom-dl#21]
### Description:
coom-dl release 0.72 does not appear to recognise any existing folders created by previous versions as the folder name template has changed. This results in it re-downloading all content into a new folder using a new folder name, instead of checking existing folders to skip content that has already been downloaded.

Release 0.72 is now adding an space character at the start of folder names (e.g. instead of [creatorname] there is an added blankspace character [ creatorname], and also adds "(Coomer Creator)" to the end of the folder name too.

### Steps to reproduce the behaviour:
If you have any existing folders from previous versions like 0.5, they will be named with just the creator's name:
"funsizedasian"
Running 0.72 for the same creator will create a new folder and will re-download all content without checking for existing items to skip as the existing folder is ignored. This new folder would be named:
" funsizedasian (Coomer Creator)"

### Workaround:
Using Windows, you cannot manually rename a folder to have a space at the start of the name, As a workaround, you could run coom-dl 0.72 first to have it create the new folder (with a space at the start of the folder name), and then copy contents of old folders into the new folder during the crawl so that coom-dl will check for items to skip later.

**Comment by ryaneford** [comment]
I am seeing the same issue myself.  If we can adjust the naming scheme to not have the space and just have the username withou the (Coomer Creator) maybe?

**Comment by notFaad** [comment]
[Feature] File name Legacy Mode
