### ISSUE TITLE
[BUG] doesnt fully download/error with big creators 

### ISSUE THREAD

**Issue by lightsaaa** [notFaad/coom-dl#35]
![Screenshot 2024-06-07 220713](https://github.com/notFaad/coom-dl/assets/157991474/9e030537-811a-497f-b993-9a9c16cd0a0f)
Hey, it seems like the scraper never fully downloads someone's content. Every time I launch a search, new stuff pops up, and I keep getting errors when dealing with a creator who has around 100 pages of content.

**Comment by notFaad** [comment]
Please use version 0.75 it has a new crawler that doesn't parse html
