### ISSUE TITLE
Coom DL no longer grabbing pictures from Coomer.Party links

### ISSUE THREAD

**Issue by 10TonProgrammer** [notFaad/coom-dl#7]
Hello,

As the title suggest, it would seem like whenever I grab content from a Coomer.Party link, no more pictures are taken and I always end up with only videos. 

I haven't touched the code and re-downloading didn't fix the issue. 

To be honest to me this is perfect as I only care about videos but still, maybe an option to filter only for photos/videos could be interesting once the issue is fixed.

**Comment by Methtallica** [comment]
I’m running into the same issue as well.

**Comment by TheSeventhCode** [comment]
Me as well.

**Comment by euronymus319** [comment]
the same problem, i think this problem starts four days ago, i don't know if is for some update in coomer web

**Comment by euronymus319** [comment]
i checked and this is just a problem with  coomer's links .someone know about some update?

**Comment by TheSeventhCode** [comment]
@notFaad, are you aware of this?

**Comment by Thymreia84** [comment]
same here for both coomer and kemono

**Comment by dudebroguy45** [comment]
> > Hello,
> > As the title suggest, it would seem like whenever I grab content from a Coomer.Party link, no more pictures are taken and I always end up with only videos.
> > I haven't touched the code and re-downloading didn't fix the issue.
> > To be honest to me this is perfect as I only care about videos but still, maybe an option to filter only for photos/videos could be interesting once the issue is fixed.
> 
> Coomer.party have updated their site and the image selector is no longer finding the image. The issue is on [line 225](https://github.com/notFaad/coom-dl/blob/a7be8819bc0281eb1d2b1535feea3ace63643690/lib/coomercrawl.dart#L225):
> 
> `"div.post__thumbnail > a"); //post__attachment-link`
> 
> To resolve it change that code to:
> 
> `"div.post__thumbnail a"); //post__attachment-link`
> 
> Build and run the app again and it should work with images.

Can you please explain how to build and run the app again after making the changes? Do you use Visual Studio Code with flutter/dart or am I lost

**Comment by firebirdsonic** [comment]
> > > Hello,
> > > As the title suggest, it would seem like whenever I grab content from a Coomer.Party link, no more pictures are taken and I always end up with only videos.
> > > I haven't touched the code and re-downloading didn't fix the issue.
> > > To be honest to me this is perfect as I only care about videos but still, maybe an option to filter only for photos/videos could be interesting once the issue is fixed.
> > 
> > 
> > Coomer.party have updated their site and the image selector is no longer finding the image. The issue is on [line 225](https://github.com/notFaad/coom-dl/blob/a7be8819bc0281eb1d2b1535feea3ace63643690/lib/coomercrawl.dart#L225):
> > `"div.post__thumbnail > a"); //post__attachment-link`
> > To resolve it change that code to:
> > `"div.post__thumbnail a"); //post__attachment-link`
> > Build and run the app again and it should work with images.
> 
> Can you please explain how to build and run the app again after making the changes? Do you use Visual Studio Code with flutter/dart or am I lost

Assuming you have Dart and Flutter installed. Go into the project > make the changes as suggested > Run `flutter run` in the command line and pick your device. I am on Windows so I picked Windows.

Alternatively, if you want to create an executable:

`flutter build windows --release`

**Comment by firebirdsonic** [comment]
> > > > > Hello,
> > > > > As the title suggest, it would seem like whenever I grab content from a Coomer.Party link, no more pictures are taken and I always end up with only videos.
> > > > > I haven't touched the code and re-downloading didn't fix the issue.
> > > > > To be honest to me this is perfect as I only care about videos but still, maybe an option to filter only for photos/videos could be interesting once the issue is fixed.
> > > > 
> > > > 
> > > > Coomer.party have updated their site and the image selector is no longer finding the image. The issue is on [line 225](https://github.com/notFaad/coom-dl/blob/a7be8819bc0281eb1d2b1535feea3ace63643690/lib/coomercrawl.dart#L225):
> > > > `"div.post__thumbnail > a"); //post__attachment-link`
> > > > To resolve it change that code to:
> > > > `"div.post__thumbnail a"); //post__attachment-link`
> > > > Build and run the app again and it should work with images.
> > > 
> > > 
> > > Can you please explain how to build and run the app again after making the changes? Do you use Visual Studio Code with flutter/dart or am I lost
> > 
> > 
> > Assuming you have Dart and Flutter installed. Go into the project > make the changes as suggested > Run `flutter run` in the command line and pick your device. I am on Windows so I picked Windows.
> > Alternatively, if you want to create an executable:
> > `flutter build windows --release`
> > And yeah, I use Visual Studio Code. But you can use any editor of your choice.
> 
> so the changes you're suggesting are for the 0.5 beta version? because the source i can download here is only 0.43 not 0.5

I'm using this version: https://github.com/notFaad/coom-dl/releases/tag/0.5

**Comment by firebirdsonic** [comment]
> > > > > > > Hello,
> > > > > > > As the title suggest, it would seem like whenever I grab content from a Coomer.Party link, no more pictures are taken and I always end up with only videos.
> > > > > > > I haven't touched the code and re-downloading didn't fix the issue.
> > > > > > > To be honest to me this is perfect as I only care about videos but still, maybe an option to filter only for photos/videos could be interesting once the issue is fixed.
> > > > > > 
> > > > > > 
> > > > > > Coomer.party have updated their site and the image selector is no longer finding the image. The issue is on [line 225](https://github.com/notFaad/coom-dl/blob/a7be8819bc0281eb1d2b1535feea3ace63643690/lib/coomercrawl.dart#L225):
> > > > > > `"div.post__thumbnail > a"); //post__attachment-link`
> > > > > > To resolve it change that code to:
> > > > > > `"div.post__thumbnail a"); //post__attachment-link`
> > > > > > Build and run the app again and it should work with images.
> > > > > 
> > > > > 
> > > > > Can you please explain how to build and run the app again after making the changes? Do you use Visual Studio Code with flutter/dart or am I lost
> > > > 
> > > > 
> > > > Assuming you have Dart and Flutter installed. Go into the project > make the changes as suggested > Run `flutter run` in the command line and pick your device. I am on Windows so I picked Windows.
> > > > Alternatively, if you want to create an executable:
> > > > `flutter build windows --release`
> > > > And yeah, I use Visual Studio Code. But you can use any editor of your choice.
> > > 
> > > 
> > > so the changes you're suggesting are for the 0.5 beta version? because the source i can download here is only 0.43 not 0.5
> > 
> > 
> > I'm using this version: https://github.com/notFaad/coom-dl/releases/tag/0.5
> 
> yeah. i used that one too. but if you look in the main.dart there's the entry that it's version 0.43 and when you build and run it definitely looks like the older version. i mean it works but i dig the newer look. haha

Ah right! I didn't look into the versions. I just went to the release page and downloaded the one that showed up first. Had to install Dart and Flutter but eventually got it to show up on my PC.

**Comment by snake2oo6** [comment]
> > > Could one of you upload the working version? I seem to be having infinite problems getting mine to work and honestly I cannot be bothered learning Visual Studio Code and all the other things from scratch, thanks! @firebirdsonic @Thymreia84
> > 
> > 
> > I've added a retry to it that retries a failed download 3 times. It isn't anything sophisticated and I'm not sure what the throttle is like for Coomer.Party so there are no timeouts (I did add it but took it out as I feel it requires further investigation).
> > [coomer_dl.zip](https://github.com/notFaad/coom-dl/files/13540457/coomer_dl.zip) - the zip file contains a Windows executable.
> > You may see files with 162 bytes but that isn't from my change. That is what it is like in the latest release. I added a retry and fixed the image issue. I left everything else as it was.
> > If anyone runs into a warning of unsafe download, you can run the zip through a virus scanner: https://www.virustotal.com/gui/url/93ae2279d59b49eae3bae3c93b315ea7785469181e119004e9373303bb934ed9?nocache=1
> 
> It works. Thank you!!!!

It is working thank you
but how to know if something did not download to retry

**Comment by snake2oo6** [comment]
> > Could one of you upload the working version? I seem to be having infinite problems getting mine to work and honestly I cannot be bothered learning Visual Studio Code and all the other things from scratch, thanks! @firebirdsonic @Thymreia84
> 
> I've added a retry to it that retries a failed download 3 times. It isn't anything sophisticated and I'm not sure what the throttle is like for Coomer.Party so there are no timeouts (I did add it but took it out as I feel it requires further investigation).
> 
> [coomer_dl.zip](https://github.com/notFaad/coom-dl/files/13540457/coomer_dl.zip) - the zip file contains a Windows executable.
> 
> You may see files with 162 bytes but that isn't from my change. That is what it is like in the latest release. I added a retry and fixed the image issue. I left everything else as it was.
> 
> If anyone runs into a warning of unsafe download, you can run the zip through a virus scanner: https://www.virustotal.com/gui/url/93ae2279d59b49eae3bae3c93b315ea7785469181e119004e9373303bb934ed9?nocache=1

It is working thank you
But is there a way to know if something did not download to retry

**Comment by firebirdsonic** [comment]
> > > Could one of you upload the working version? I seem to be having infinite problems getting mine to work and honestly I cannot be bothered learning Visual Studio Code and all the other things from scratch, thanks! @firebirdsonic @Thymreia84
> > 
> > 
> > I've added a retry to it that retries a failed download 3 times. It isn't anything sophisticated and I'm not sure what the throttle is like for Coomer.Party so there are no timeouts (I did add it but took it out as I feel it requires further investigation).
> > [coomer_dl.zip](https://github.com/notFaad/coom-dl/files/13540457/coomer_dl.zip) - the zip file contains a Windows executable.
> > You may see files with 162 bytes but that isn't from my change. That is what it is like in the latest release. I added a retry and fixed the image issue. I left everything else as it was.
> > If anyone runs into a warning of unsafe download, you can run the zip through a virus scanner: https://www.virustotal.com/gui/url/93ae2279d59b49eae3bae3c93b315ea7785469181e119004e9373303bb934ed9?nocache=1
> 
> It is working thank you But is there a way to know if something did not download to retry

Yeah, I've added that to the messages. I've forked the project as it'll be easier for me to push updates there than in the comments here. You can download and view the release notes here: https://github.com/firebirdsonic/coom-dl/releases/tag/1.0.0

Caveat: I've never programmed in Dart before but I'll try my best to resolve any issues while OP is away. When OP is back, I'll hand it back over to him.

**Comment by iSupremacy** [comment]
@firebirdsonic Such a heroic individual <3

**Comment by TuckerWarlock** [comment]
@firebirdsonic Do you plan on opening up a PR from your forked branch to get those changes merged into this repo?

**Comment by Kozi801** [comment]
Hello, I have the same issue, I am new to the app, using it for the first time, if I understand, if I apply the current fix for line 225, it should now work for images?

**Comment by JDR11** [comment]
@firebirdsonic Would you be able to make a commit on your fork with your changes to the source code so people can build for versions other than Windows?

**Comment by snake2oo6** [comment]
This software is quite valuable.
It must be kept operational and up to date.
It is now too slow; I'm not sure why.
Kindly resolve the problem.

**Comment by notFaad** [comment]
Fixed with 0.72
