### ISSUE TITLE
Download speed is really slow 

### ISSUE THREAD

**Issue by DJboutit** [notFaad/coom-dl#9]
Download speed of this program seems to be really slow I have no idea what I am downloading at I just know it is not 10mbps+.  I have a 1Gbit connection it should not take 90min to 3hrs to download a 6gb to 20gb pack.  I am not saying I should be getting 25mbps+ real speed 10mbps to 15mbps would be just fine.

**Comment by notFaad** [comment]
Coomer.su has really slow servers it's normal for the downloads to be very slow.
